spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:alcodb
    username: sa
    password:

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  data:
    redis:
      host: localhost
      port: 6379

  jwt:
    key: ${JWT_SECRET_KEY}
    validity:
      atk: 300000
      rtk: 3000000

server:
  port: 8080